using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManagerSurvivor : MonoBehaviour
{
    public GameObject player;
    public GameObject floorTile;
    public int playerLifes = 3;
    public int numberOfPlayers = 2;

    private Transform transformBase;
    private GameObject[] players;

    // Start is called before the first frame update
    void Start()
    {
        floor();

        players = new GameObject[numberOfPlayers];

        for (int i = 0; i < numberOfPlayers; i++)
        {
            players[i] = Instantiate(player, transformBase);
            players[i].GetComponent<PlayerMovement>().playerIndex = i;
        }
        
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        
    }

    void floor() 
    {
        GameObject tile;
        GameObject ground = GameObject.Find("Ground");

        for (float i = 0.32f; i < 7; i+=0.64f)
        {
            for (float j = 0.32f; j < 5; j+=0.64f)
            {
                tile = Instantiate(floorTile, transformBase);
                tile.transform.position += new Vector3(i, j, 0);
                tile.transform.SetParent(ground.GetComponent<Transform>());
            }
        }

        for (float i = -0.32f; i > -7; i-=0.64f)
        {
            for (float j = 0.32f; j < 5; j+=0.64f)
            {
                tile = Instantiate(floorTile, transformBase);
                tile.transform.position += new Vector3(i, j, 0);
                tile.transform.SetParent(ground.GetComponent<Transform>());
            }
        }

        for (float i = 0.32f; i < 7; i+=0.64f)
        {
            for (float j = -0.32f; j > -5; j-=0.64f)
            {
                tile = Instantiate(floorTile, transformBase);
                tile.transform.position += new Vector3(i, j, 0);
                tile.transform.SetParent(ground.GetComponent<Transform>());
            }
        }

        for (float i = -0.32f; i > -7; i-=0.64f)
        {
            for (float j = -0.32f; j > -5; j-=0.64f)
            {
                tile = Instantiate(floorTile, transformBase);
                tile.transform.position += new Vector3(i, j, 0);
                tile.transform.SetParent(ground.GetComponent<Transform>());
            }
        }

    }
}
